### ISSUE TITLE
中文数据集下add_token_spans

### ISSUE THREAD

**Issue by Power886** [131250208/JointExtraction#31]
已解决

**Comment by guanxichouqu** [comment]
你好 我想用TPLinker在中文数据集上运行，我想请问一下需要准备什么 改哪个地方 我是刚入门的小白 可以请教一下经验吗

**Comment by YuJiaYi1412** [comment]
> 你好 我想用TPLinker在中文数据集上运行，我想请问一下需要准备什么 改哪个地方 我是刚入门的小白 可以请教一下经验吗

我也是小白，我看解决了，能请教一下吗？
