### ISSUE TITLE
请问数据集中的char_span有什么作用呢？

### ISSUE THREAD

**Issue by YYGe01** [131250208/JointExtraction#32]
作者您好，我是直接下载的您清洗好的数据集进行debug。

然后我感觉训练评估和预测都是基于token的操作，并且感觉sub_char_span和obj_char_span 没有发挥作用，是否可以舍弃呢

**Comment by 131250208** [comment]
不能，char_span用于在原文中截取实体

**Comment by YYGe01** [comment]
> 不能，char_span用于在原文中截取实体

谢谢回复，但是我只要能传递原始文本text，和通过tok2char_span = codes["offset_mapping"]，也可以截取实体，我看作者在后面的处理中也是这么用的呢。比如下面截取实体用的是tok2char_span，得到原文中的位置。

我在您给的代码中，没有看到数据集中的char_span的具体作用呢，不知道是哪块逻辑用到了呢。

```
            char_span_list = tok2char_span[sp[0]:sp[1] + 1]
            char_sp = [char_span_list[0][0], char_span_list[-1][1]]
            ent_text = text[char_sp[0]:char_sp[1]] 
            entity = {
                "type": ent_type,
                "text": ent_text,
                "tok_span": [sp[0], sp[1] + 1],
                "char_span": char_sp,
            }
```

**Comment by 131250208** [comment]
@YYGe01 char_span是唯一确定的，用BERT和不用BERT时token的粒度是不确定的，所以char_span是tok_span的依据，当然，如果你对不同encoder使用不同的数据，然后分别打两种tok_span也是可以的，输出输入都有char_span是为了统一，以及提供充足的信息，以免总是需要用map去转换成char_span。
