### ISSUE TITLE
tplinker-plus关系acc低

### ISSUE THREAD

**Issue by enbacoo** [131250208/JointExtraction#33]
同一个中文数据集试验了tplinker和plus，tplinker f1能到74，但plus 的rel f1只有54，其中acc很高86，召回就只有39了，这个可能是因为什么导致的呢

**Comment by 131250208** [comment]
这个可能需要你自己去探索，检查一下参数吧

**Comment by enbacoo** [comment]
> 这个可能需要你自己去探索，检查一下参数吧

好的，多谢哈~

**Comment by YuJiaYi1412** [comment]
请问为什么一个epcho下来f1和acc都是0
![image](https://github.com/user-attachments/assets/d62cd044-6957-451f-badc-aeba9e83650c)
