### ISSUE TITLE
Did you apply muilti EH-ETs in TPLinker-plus?

### ISSUE THREAD

**Issue by jarork** [131250208/JointExtraction#43]
Hi dear author, your project is helping us a lot, thanks again! TPLinker Plus is really a strong model especially for lots of nested entities and complicated relations.

I notice that a single word or a word group can be predicted as two entity at the same time. e.g. "orange" -> fruit and "orange" -> color at the same time.

What makes it possible to tag 1+ entity labels on the same char_span? I learned that the different entity label represent the different number on TPLinker's EH-ET; which means it's not possible to have 1+ entity types on the same span. (must be orange -> fruit or orange -> color, but not the same time)

Did you apply muiltiple EH-ETs in TPLinker-plus? (Each EH-ET represents each entity type)

**Comment by 131250208** [comment]
Hi, you can check out the outputs and the loss function of TPLinkerPlus and you would figure out that it predicts multiple labels for each span.
