### ISSUE TITLE
What does mean of the metric in train log?

### ISSUE THREAD

**Issue by LawsonAbs** [131250208/JointExtraction#45]
What does mean of the metric in train log? As shown in the following picture.
![image](https://user-images.githubusercontent.com/35190068/116837177-e6aa6600-abfb-11eb-998f-f87fb19c759d.png)

**Comment by jarork** [comment]
The accuracies of predicting entity labels and subject head to object head relations.

![image](https://user-images.githubusercontent.com/36119760/116991246-d9c66900-ad06-11eb-9bca-97dce65dcb12.png)

**Comment by 131250208** [comment]
![image](https://user-images.githubusercontent.com/7437595/118744516-0e99fa80-b887-11eb-80ea-1c0c75944466.png)

**Comment by LawsonAbs** [comment]
thank you~
