### ISSUE TITLE
def decode_rel()方法运行时间过长

### ISSUE THREAD

**Issue by sssirus** [131250208/JointExtraction#56]
使用tplinker_plus在gpu上运行valid过程时，发现运行时间很长，远远超过了训练时间。经过排查，发现是decode_rel()方法执行了很长时间。
请问有什么解决方法？

**Comment by 131250208** [comment]
如果是前几轮的问题，debug看是不是预测结果里1太多了，如果是的话就是训练不充分导致的，训练超参的设置可能有问题（比如batch_size太大）。要么修改超参，要么修改代码让模型多训练几轮再进行valid过程。

**Comment by sssirus** [comment]
减少了batch，修改代码多轮train之后进行valid，增加迭代次数后，问题已经解决。感谢！
